### ISSUE TITLE
f26 modules in f27

### ISSUE THREAD

**Issue by langdon** [fedora-modularity/f27-content-tracking#17]
How hard would it be to fix up the f26 modules to work with the f27 base? Could we easily have two streams of a few things?

**Comment by mattdm** [comment]
+1 ♥ ❤ ♥ ❤ ♥

**Comment by james-antill** [comment]
Adding the repo. file mostly just works, I tried and you can install @httpd:f26/default and @postgresql:f26/default ... however neither have changed much. @nginx:f26 fails due to deps on libprofiler.

Note that the bikeshed repo. doesn't contain the nodejs module builds, which have a master and 6 stream.

**Comment by james-antill** [comment]
Issue #18 is related to this too, in that as that gets fixed this becomes better.

**Comment by langdon** [comment]
@james-antill can you add "repo" and "stream" names for this stuff to the README? So when I go do my next variants-modular.xml PR I can pick them up?

**Comment by alexxa** [comment]
@james-antill @whitel is it still a valid issue? Please update, or close.

**Comment by langdon** [comment]
We don't see a way to make this work directly. We would have to re-create all the modules.
