### ISSUE TITLE
Use meaningful module stream names

### ISSUE THREAD

**Issue by sctweedie** [fedora-modularity/f27-content-tracking#18]
A major point of modularity is to support content streams that have lifecycles independent of the base distribution.

So module streams should have names reflecting the lifecycle of the module content itself, not a generic stream name like the current "master".

Modules like "http", "samba", "bind" etc. should have a stream name reflecting the (major) version of the primary component.

Open question: should platform&host modules use stream name "27" or something else?

**Comment by mattdm** [comment]
Do we have guidance on "how major is major"? That is, do we have Python stream 3 or Python stream 3.6? 

What should happen with projects that have a single stream and rev frequently but yet are generally (or even rigorously) backwards-compatible? These often do not have major version numbers in a meaningful sense — look at systemd for example (and imagine some leaf module using the same scheme). Or for that matter, something like the kernel where there are major and minor version numbers but they've been defined to _not really mean anything_?

Or, what about projects which have a major versions but distinct devel and stable streams within that major version?

**Comment by igor-raits** [comment]
@mattdm I think for python we are going to have `python2`, `python3`, `python3.5`, `python2.6` modules

**Comment by mattdm** [comment]
@ignatenkobrain That makes sense to me. Presumably `python3` will point to some-and-probably-the-latest `.y` release and be expected to upgrade between them even though there may be some minor breaking changes? Will there be a service level designator or some other tag making that clear? Or will that just go in the description? What will the EOL for `python3` be?

**Comment by langdon** [comment]
@mattdm https://fedoraproject.org/wiki/Module:Guidelines?rd=Fedora_Packaging_Guidelines_for_Modules#Module_name.2C_update_stream.2C_version.2C_context_and_architecture should be answering your questions. If it needs expansion, let's file a different ticket. I think @sctweedie is saying "let's make these mods to these particular modules" rather than, "how do i know what the name should be?"

@KarstenHopp do you think this is something you could change?

**Comment by mattdm** [comment]
@whitel Ah that's fair -- I don't get notifications for wiki edits but do for these tickets :)

**Comment by sctweedie** [comment]
@mattdm The stream name needs to be able to distinguish between significant distinct streams.

For python, we want the user to be able to choose 3.4, 3.5, 3.6 etc.  So the stream name needs to include x.y.

I don't expect us to have a "3" or "python3" stream name.  There will absolutely be a python3 *module*, but it should have streams named 3.y.  

If a user only wants python3 and doesn't care about which minor version they get, they should just require the "python3" rpm and let the system profile choose which module stream they end up with.

**Comment by igor-raits** [comment]
@sctweedie AIUI, we will **not** make `python3` module with `3.4`, `3.5`, `3.6` streams because you can't enable multiple streams in parallel, so in Fedora there will be modules with names `python3.4`, `python3.5`

**Comment by sgallagher** [comment]
@ignatenkobrain I'm not sure if you're confusing streams with profiles or if you mean that you're developing separate modules for the purposes of parallel installation (which I thought we were not actually planning to do).

Can you provide more details here?

**Comment by igor-raits** [comment]
@sgallagher no, I'm not talking about profiles at all...

Basically, today we have python33, python34, python35, python3 packages parallel-installable in Fedora. Natively with modules I would think that they map to one module with streams master, 3.5, 3.4, 3.3.. However, it was decided that we don't support enabling more than 1 stream at the same time. So Python guys decided to go with different **modules** rather than streams. Hopefully now it is more clear.

**Comment by sgallagher** [comment]
@ignatenkobrain So you *are* looking at making these parallel-installable. I'd like to recommend that we should actually handle this differently. There should be a "primary" module called `python` who should have multiple streams, one for each X.Y release. This one should (rightfully) be only allowed to install one of these streams at a time. This module should own the standard filenames in `/usr/bin` such as `/usr/bin/python` and `/usr/bin/easy_install`

Then, you can also have a set of alternative modules (e.g. `alt-python34`) that are parallel-installable but will keep their binaries in an alternative path (such as `/opt/python34/bin`).

**Comment by igor-raits** [comment]
@sgallagher I definitely do because the goal of that is that user can install tox and his python module will be tested against all python versions. This is kinda what makes ubuntu or other distributions to succeed in CI environments.

**Comment by sgallagher** [comment]
@ignatenkobrain I'm not saying it's an unwelcome goal. I'm saying it was not planned to be available like that from the start, so I am offering a suggestion on how to build alternative versions that remains compatible with our general plan for modularity.

**Comment by igor-raits** [comment]
@sgallagher well, that's the plan for now (apart from different names / paths). But honestly I don't like this.

**Comment by sgallagher** [comment]
@ignatenkobrain Can you please be more descriptive in your replies? For example, please explain why you don't like my proposal. I think it's important (critical, really), that we have a single module that owns the well-known paths. I'm not opposed to having alternative versions available, but they really should be _add-ons_ and have no opportunity to interfere with default operation.

End-users should be able to say "My application needs python 3.5, so that's the stream I'll install from the python module and I can trust that `/usr/bin/python3` will be 3.5". The CI case, while interesting, is just as well solved by requiring the explicit use of `/opt/python33/bin/python3` IMHO. I'm much more concerned about making sure that end-user deployments don't get unpleasant surprises.

**Comment by langdon** [comment]
I think this ticket has gotten pretty far away from the original issue. Can I propose that @sgallagher & @ignatenkobrain file something in the [python3 module](https://github.com/modularity-modules/python3)? or if we want a "global policy" in the [modularity wg project](https://pagure.io/modularity)? I want to be able to close this when we have fixed the names of the streams "for now." If we want to change/determine the policy, that should be a separate conversation.

**Comment by mattdm** [comment]
(Is sorry.)

**Comment by nphilipp** [comment]
I think the discussion is done, so I'll close this now.
